[package]
name = "othello"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.17.11"
lazy_static = "1.5.0"
regex = "1.11.1"
tar = "0.4.44"
thiserror = "2.0.11"
zstd = "0.13.3"

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"
